version: '3.7'

services:
  app:
    build: .
    volumes:
    - .:/app
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
