# Generated by Django 3.0.5 on 2020-04-03 19:38

import common.enums
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('description', models.CharField(default='Description', max_length=1024)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Plants', 'Plants')], default=common.enums.Categories['Food'], max_length=255)),
                ('city', models.CharField(choices=[('Warsaw', 'Warsaw'), ('Wroclaw', 'Wroclaw'), ('Cracow', 'Cracow'), ('Lodz', 'Lodz'), ('Szczecin', 'Szczecin')], default=common.enums.Cities['Warsaw'], max_length=255)),
                ('distance', models.CharField(default='3.8 km from you', max_length=255)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2020, 4, 5, 19, 38, 54, 505805))),
                ('photo_url', models.CharField(default='https://images.unsplash.com/photo-1489416955296-6737e8d74e84?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=400', max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
