# Generated by Django 3.0.5 on 2020-04-03 21:32

import common.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_adjust_enums'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='clients',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_date',
            field=models.DateTimeField(default=common.utils.get_default_delivery_date),
        ),
        migrations.AlterField(
            model_name='offer',
            name='distance',
            field=models.CharField(default=common.utils.get_default_distance, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photo_url',
            field=models.CharField(default=common.utils.get_default_photo_url, max_length=2048),
        ),
    ]
