# Generated by Django 3.0.5 on 2020-04-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_add_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='clients',
        ),
    ]
