# Generated by Django 3.0.5 on 2020-04-04 09:20

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=common.utils.get_default_product_name, max_length=255),
        ),
    ]
